In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# 1. 加载数据
train = pd.read_csv('train.csv')  # 训练数据
test = pd.read_csv('test.csv')    # 测试数据

In [2]:
train['country']

,id,date,country,store,product,num_sold
0,0,2010-01-01,Canada,Discount Stickers,Holographic Goose,NaN
1,1,2010-01-01,Canada,Discount Stickers,Kaggle,973.0
2,2,2010-01-01,Canada,Discount Stickers,Kaggle Tiers,906.0
3,3,2010-01-01,Canada,Discount Stickers,Kerneler,423.0
4,4,2010-01-01,Canada,Discount Stickers,Kerneler Dark Mode,491.0
...,...,...,...,...,...,...
230125,230125,2016-12-31,Singapore,Premium Sticker Mart,Holographic Goose,466.0
230126,230126,2016-12-31,Singapore,Premium Sticker Mart,Kaggle,2907.0
230127,230127,2016-12-31,Singapore,Premium Sticker Mart,Kaggle Tiers,2299.0
230128,230128,2016-12-31,Singapore,Premium Sticker Mart,Kerneler,1242.0
230129,230129,2016-12-31,Singapore,Premium Sticker Mart,Kerneler Dark Mode,1622.0

In [3]:
train['days'] = pd.to_datetime(train['date'])
test['days'] = pd.to_datetime(test['date'])
base_date = pd.to_datetime('2010-01-01')
train['days'] = (train['days'] - base_date).dt.days
test['days'] = (test['days'] - base_date).dt.days
train['days'].head()

0    0
1    0
2    0
3    0
4    0
Name: days, dtype: int64

In [4]:
train['product'].describe()

count                230130
unique                    5
top       Holographic Goose
freq                  46026
Name: product, dtype: object

In [5]:
train = pd.get_dummies(train, columns=['country'], drop_first=True)  # 独热编码
test = pd.get_dummies(test, columns=['country'], drop_first=True)
train = pd.get_dummies(train, columns=['store'], drop_first=True)  # 独热编码
test = pd.get_dummies(test, columns=['store'], drop_first=True)

In [6]:
train['num_sold'] = train['num_sold'].fillna(0)

In [7]:
train.head()

,id,date,product,num_sold,days,country_Finland,country_Italy,country_Kenya,country_Norway,country_Singapore,store_Premium Sticker Mart,store_Stickers for Less
0,0,2010-01-01,Holographic Goose,0.0,0,False,False,False,False,False,False,False
1,1,2010-01-01,Kaggle,973.0,0,False,False,False,False,False,False,False
2,2,2010-01-01,Kaggle Tiers,906.0,0,False,False,False,False,False,False,False
3,3,2010-01-01,Kerneler,423.0,0,False,False,False,False,False,False,False
4,4,2010-01-01,Kerneler Dark Mode,491.0,0,False,False,False,False,False,False,False

In [8]:
features = ['days', 'country_Finland', 'country_Italy', 'country_Norway', 'country_Kenya', 'country_Singapore', 'store_Premium Sticker Mart', 'store_Stickers for Less']
X = train[features]
Y = train['num_sold']
X_test = test[features]

X_scaled = StandardScaler().fit_transform(X)
X_test_scaled = StandardScaler().fit_transform(X_test)

In [9]:
X_train, X_val, Y_train, Y_val = train_test_split(X_scaled, Y, test_size=0.2, random_state=42)

In [10]:
svm = SVC(kernel='rbf', C=1, gamma=0.1, random_state=42)

# 模型训练
svm.fit(X_train, Y_train)

SVC(C=1, gamma=0.1, random_state=42)

In [13]:
import numpy as np
from tqdm import tqdm
from sklearn.metrics import mean_squared_error
from sklearn.svm import SVR  # 也可换成你的模型

# 1. 假设你已经完成模型训练，如：
# model = SVR().fit(X_train, y_train)

# 2. 验证集特征和标签
#    这里以 X_val, y_val 为例

batch_size = 1000  # 每批预测多少条，可按需调整
n_samples = X_val.shape[0]

all_preds = []  # 用于保存每个批次的预测结果

# 用 tqdm 显示分批预测进度
for start_idx in tqdm(range(0, n_samples, batch_size), desc="Predicting in batches"):
    end_idx = min(start_idx + batch_size, n_samples)
    
    # 取本批次的数据和标签
    X_batch = X_val[start_idx:end_idx]
    y_batch_true = Y_val[start_idx:end_idx]
    
    # 调用模型对本批次进行预测
    y_batch_pred = svm.predict(X_batch)
    
    # 保存预测结果
    all_preds.append(y_batch_pred)
    
    # 计算本批次的 MSE
    batch_mse = mean_squared_error(y_batch_true, y_batch_pred)
    
    # 用 tqdm.write() 打印当前批次的 MSE，避免与进度条冲突
    tqdm.write(f"Batch {start_idx // batch_size} MSE: {batch_mse:.4f}")

# 合并所有批次的预测结果
all_preds = np.concatenate(all_preds, axis=0)

# 计算整体验证集上的 MSE
final_mse = mean_squared_error(Y_val, all_preds)
print(f"\nOverall Validation MSE: {final_mse:.4f}")

Predicting in batches:   2%|▏         | 1/47 [15:42<12:02:53, 942.91s/it]

Batch 0 MSE: 754308.7820

Predicting in batches:   4%|▍         | 2/47 [30:22<11:19:15, 905.67s/it]

Batch 1 MSE: 763785.7420

Predicting in batches:   6%|▋         | 3/47 [46:25<11:23:15, 931.72s/it]

Batch 2 MSE: 805434.5890

Predicting in batches:   9%|▊         | 4/47 [59:29<10:25:59, 873.47s/it]

Batch 3 MSE: 804985.4800

Predicting in batches:  11%|█         | 5/47 [1:12:26<9:47:09, 838.79s/it]

Batch 4 MSE: 675620.9650

Predicting in batches:  13%|█▎        | 6/47 [1:25:28<9:19:53, 819.35s/it]

Batch 5 MSE: 634849.0510

Predicting in batches:  15%|█▍        | 7/47 [1:38:27<8:57:24, 806.11s/it]

Batch 6 MSE: 735246.8430

Predicting in batches:  17%|█▋        | 8/47 [1:51:26<8:38:30, 797.71s/it]

Batch 7 MSE: 784729.0310

Predicting in batches:  19%|█▉        | 9/47 [2:04:31<8:22:37, 793.61s/it]

Batch 8 MSE: 743036.3050

Predicting in batches:  21%|██▏       | 10/47 [2:17:36<8:07:44, 790.93s/it]

Batch 9 MSE: 774108.1640

Predicting in batches:  23%|██▎       | 11/47 [2:30:42<7:53:37, 789.38s/it]

Batch 10 MSE: 752409.9850

Predicting in batches:  26%|██▌       | 12/47 [2:43:47<7:39:40, 788.03s/it]

Batch 11 MSE: 702809.4560

Predicting in batches:  28%|██▊       | 13/47 [2:56:50<7:25:45, 786.62s/it]

Batch 12 MSE: 819524.9640

Predicting in batches:  30%|██▉       | 14/47 [3:09:59<7:13:05, 787.43s/it]

Batch 13 MSE: 725972.0010

Predicting in batches:  32%|███▏      | 15/47 [3:23:09<7:00:19, 788.10s/it]

Batch 14 MSE: 770005.6720

Predicting in batches:  34%|███▍      | 16/47 [3:35:59<6:44:26, 782.78s/it]

Batch 15 MSE: 743279.2180

Predicting in batches:  36%|███▌      | 17/47 [3:49:09<6:32:20, 784.69s/it]

Batch 16 MSE: 707662.1430

Predicting in batches:  38%|███▊      | 18/47 [4:02:18<6:19:59, 786.20s/it]

Batch 17 MSE: 717309.8710

Predicting in batches:  40%|████      | 19/47 [4:15:32<6:07:58, 788.53s/it]

Batch 18 MSE: 752800.5480

Predicting in batches:  43%|████▎     | 20/47 [4:28:40<5:54:47, 788.43s/it]

Batch 19 MSE: 830181.4960

Predicting in batches:  45%|████▍     | 21/47 [4:41:46<5:41:16, 787.56s/it]

Batch 20 MSE: 681992.7520

Predicting in batches:  47%|████▋     | 22/47 [4:54:55<5:28:17, 787.91s/it]

Batch 21 MSE: 823860.4650

Predicting in batches:  49%|████▉     | 23/47 [5:08:02<5:15:06, 787.76s/it]

Batch 22 MSE: 747453.9830

Predicting in batches:  51%|█████     | 24/47 [5:21:10<5:02:00, 787.83s/it]

Batch 23 MSE: 694276.2580

Predicting in batches:  53%|█████▎    | 25/47 [5:34:20<4:49:07, 788.51s/it]

Batch 24 MSE: 743635.8480

Predicting in batches:  55%|█████▌    | 26/47 [5:47:31<4:36:11, 789.12s/it]

Batch 25 MSE: 697449.9210

Predicting in batches:  57%|█████▋    | 27/47 [6:00:39<4:22:57, 788.89s/it]

Batch 26 MSE: 733987.0440

Predicting in batches:  60%|█████▉    | 28/47 [6:13:51<4:10:05, 789.76s/it]

Batch 27 MSE: 732878.5020

Predicting in batches:  62%|██████▏   | 29/47 [6:27:02<3:57:05, 790.28s/it]

Batch 28 MSE: 743779.6540

Predicting in batches:  64%|██████▍   | 30/47 [6:39:59<3:42:47, 786.30s/it]

Batch 29 MSE: 751076.3410

Predicting in batches:  66%|██████▌   | 31/47 [6:53:09<3:29:57, 787.35s/it]

Batch 30 MSE: 676046.4550

Predicting in batches:  68%|██████▊   | 32/47 [7:06:20<3:17:05, 788.37s/it]

Batch 31 MSE: 706329.3580

Predicting in batches:  70%|███████   | 33/47 [7:19:27<3:03:51, 787.95s/it]

Batch 32 MSE: 724429.0330

Predicting in batches:  72%|███████▏  | 34/47 [7:32:39<2:51:00, 789.28s/it]

Batch 33 MSE: 660123.2930

Predicting in batches:  74%|███████▍  | 35/47 [7:45:53<2:38:05, 790.46s/it]

Batch 34 MSE: 658279.5920

Predicting in batches:  77%|███████▋  | 36/47 [7:58:59<2:24:41, 789.19s/it]

Batch 35 MSE: 708166.0520

Predicting in batches:  79%|███████▊  | 37/47 [8:12:10<2:11:38, 789.86s/it]

Batch 36 MSE: 732900.7880

Predicting in batches:  81%|████████  | 38/47 [8:25:25<1:58:43, 791.46s/it]

Batch 37 MSE: 819884.6280

Predicting in batches:  83%|████████▎ | 39/47 [8:38:35<1:45:27, 790.98s/it]

Batch 38 MSE: 659178.0310

Predicting in batches:  85%|████████▌ | 40/47 [8:51:27<1:31:36, 785.22s/it]

Batch 39 MSE: 812492.2820

Predicting in batches:  87%|████████▋ | 41/47 [9:04:35<1:18:35, 785.92s/it]

Batch 40 MSE: 716544.2970

Predicting in batches:  89%|████████▉ | 42/47 [9:17:50<1:05:43, 788.76s/it]

Batch 41 MSE: 696570.8500

Predicting in batches:  91%|█████████▏| 43/47 [9:31:01<52:37, 789.32s/it]

Batch 42 MSE: 789878.2920

Predicting in batches:  94%|█████████▎| 44/47 [9:44:11<39:28, 789.59s/it]

Batch 43 MSE: 668310.8620

Predicting in batches:  96%|█████████▌| 45/47 [9:57:22<26:20, 790.10s/it]

Batch 44 MSE: 747683.4910

Predicting in batches:  98%|█████████▊| 46/47 [10:10:35<13:11, 791.05s/it]

Batch 45 MSE: 689145.7220

Predicting in batches: 100%|██████████| 47/47 [10:10:57<00:00, 779.94s/it]

Batch 46 MSE: 1147375.4615

Overall Validation MSE: 735328.8546

In [14]:
print("支持向量：", svm.support_vectors_)

支持向量： [[-1.59860783 -0.4472136  -0.4472136  ... -0.4472136  -0.70710678
   1.41421356]
 [ 1.3859117  -0.4472136  -0.4472136  ... -0.4472136  -0.70710678
  -0.70710678]
 [-0.16257029 -0.4472136  -0.4472136  ... -0.4472136  -0.70710678
  -0.70710678]
 ...
 [ 0.24385543 -0.4472136  -0.4472136  ... -0.4472136   1.41421356
  -0.70710678]
 [ 0.7369853  -0.4472136  -0.4472136  ... -0.4472136   1.41421356
  -0.70710678]
 [-0.24927444 -0.4472136  -0.4472136  ... -0.4472136   1.41421356
  -0.70710678]]

In [15]:
print("决策函数的系数：", svm.dual_coef_)

决策函数的系数： [[ 0.  0.  0. ... -1. -1. -1.]
 [ 0.  0.  0. ... -1. -1. -1.]
 [ 0.  0.  0. ... -1. -1. -1.]
 ...
 [ 0.  0.  0. ... -1. -1. -1.]
 [ 0.  0.  0. ...  1. -1. -1.]
 [ 0.  0.  0. ...  1.  1. -1.]]